# require 'faker'

# 10.times do
#   department = Department.create(name: Faker::Company.industry)
# end

# Department.create(name: 'Clothing')
# Department.create(name: 'Furniture')
# Department.create(name: 'Home Appliances')
# Department.create(name: 'Toys')
# Department.create(name: 'Cosmetics')
# Department.create(name: 'Houseware')
# Department.create(name: 'Sporting Goods')
# Department.create(name: 'Hardware & Tools')

# Item.create(name: 'Shirt')
# Item.create(name: 'Pants')
# Item.create(name: 'Shorts')
# Item.create(name: 'Chair')
# Item.create(name: 'Couch')
# Item.create(name: 'Table')
# Item.create(name: 'Oven')
# Item.create(name: 'Dishwasher')
# Item.create(name: 'Dryer')
# Item.create(name: 'Doll')
# Item.create(name: 'Truck')
# Item.create(name: 'Bike')
# Item.create(name: 'Shampoo')
# Item.create(name: 'Mascara')
# Item.create(name: 'Lipstick')
# Item.create(name: 'Lightbulbs')
# Item.create(name: 'Trash Bags')
# Item.create(name: 'Garden Hose')
# Item.create(name: 'Baseball Bat')
# Item.create(name: 'Soccer Ball')
# Item.create(name: 'Fishing Pole')
# Item.create(name: 'Hammer')
# Item.create(name: 'Painters Tape')
# Item.create(name: 'Lawn Mower')